### ISSUE TITLE
Odd character instead of "x" in printed tibble dimensions

### ISSUE THREAD

**Issue by sfirke** [jennybc/reprex#73]
```
library(dplyr)
as_data_frame(mtcars)
reprex::reprex(NULL, "gh") # after highlighting lines 1-2
```

When I run lines 1-2 normally, my console output starts:
`# A tibble: 32 × 11`

But the reprex output is:
`#> # A tibble: 32 Ã— 11`

My current approach is just to manually type "x" over the offending character in the result.

**Comment by jennybc** [comment]
Yeah, I inherit this problem from tibble itself.

https://github.com/tidyverse/tibble/pull/192

If you update tibble does that help?

**Comment by sfirke** [comment]
It doesn't, I updated to the current version of tibble on GitHub and I still get the odd character.

My `session_info()`:
```
> session_info()
Session info -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-03-02                  

Packages ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                            
 assertthat   0.1        2013-12-06 CRAN (R 3.3.0)                    
 backports    1.0.5      2017-01-18 CRAN (R 3.3.2)                    
 callr        1.0.0.9000 2017-02-09 Github (mangothecat/callr@c02300a)
 clipr        0.3.2      2017-01-09 CRAN (R 3.3.2)                    
 curl         2.3        2016-11-24 CRAN (R 3.3.2)                    
 DBI          0.5-1      2016-09-10 CRAN (R 3.3.1)                    
 devtools   * 1.12.0     2016-06-24 CRAN (R 3.3.2)                    
 digest       0.6.12     2017-01-27 CRAN (R 3.3.2)                    
 dplyr      * 0.5.0.9000 2017-02-27 Github (hadley/dplyr@8430adc)     
 evaluate     0.10       2016-10-11 CRAN (R 3.3.2)                    
 git2r        0.18.0     2017-01-01 CRAN (R 3.3.2)                    
 htmltools    0.3.5      2016-03-21 CRAN (R 3.3.2)                    
 httr         1.2.1      2016-07-03 CRAN (R 3.3.1)                    
 knitr        1.15.1     2016-11-22 CRAN (R 3.3.2)                    
 magrittr     1.5        2014-11-22 CRAN (R 3.3.0)                    
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.0)                    
 pacman     * 0.4.1      2016-03-30 CRAN (R 3.3.0)                    
 R6           2.2.0      2016-10-05 CRAN (R 3.3.1)                    
 Rcpp         0.12.9.3   2017-02-27 Github (RcppCore/Rcpp@c76a5c3)    
 reprex       0.1.0      2017-01-10 CRAN (R 3.3.2)                    
 rmarkdown    1.3        2016-12-21 CRAN (R 3.3.1)                    
 rprojroot    1.2        2017-01-16 CRAN (R 3.3.2)                    
 rstudioapi   0.6        2016-06-27 CRAN (R 3.3.1)                    
 stringi      1.1.2      2016-10-01 CRAN (R 3.3.2)                    
 stringr      1.2.0      2017-02-18 CRAN (R 3.3.2)                    
 tibble     * 1.2-15     2017-03-02 Github (tidyverse/tibble@4c32758) 
 whisker      0.3-2      2013-04-28 CRAN (R 3.3.0)                    
 withr        1.0.2      2016-06-20 CRAN (R 3.3.1)    
```

**Comment by jennybc** [comment]
That is sad. I will have to look into it.

Does this happen whenever you render `.R` files that print a tibble or is it somehow unique to reprex output? Would you check that for me?

**Comment by masalmon** [comment]
I get the same issue. I have installed `tibble` latest version. Also I'm stressing out about making a non reproducible example :grimacing: 

# Code
```r
library(tidyr)
test <- data.frame(x = letters[1:3], 
           y = 1:3,
           z = c(1, 1, 2)) %>% 
  nest(-y, -z)
print(test)
```

# with `reprex()`

``` r
library(tidyr)
#> Warning: package 'tidyr' was built under R version 3.3.2
test <- data.frame(x = letters[1:3], 
           y = 1:3,
           z = c(1, 1, 2)) %>% 
  nest(-y, -z)
print(test)
#> # A tibble: 3 Ã— 3
#>       y     z             data
#>   <int> <dbl>           <list>
#> 1     1     1 <tibble [1 Ã— 1]>
#> 2     2     1 <tibble [1 Ã— 1]>
#> 3     3     2 <tibble [1 Ã— 1]>
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info --------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.3.1 (2016-06-21)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Spanish_Spain.1252          
#>  tz       Europe/Paris                
#>  date     2017-03-08
#> Packages ------------------------------------------------------------------
#>  package    * version    date       source                            
#>  assertthat   0.1        2013-12-06 CRAN (R 3.2.2)                    
#>  backports    1.0.5      2017-01-18 CRAN (R 3.3.2)                    
#>  DBI          0.5-1      2016-09-10 CRAN (R 3.3.2)                    
#>  devtools     1.12.0     2016-06-24 CRAN (R 3.3.2)                    
#>  digest       0.6.12     2017-01-27 CRAN (R 3.3.2)                    
#>  dplyr        0.5.0.9000 2017-01-26 Github (hadley/dplyr@92a13a3)     
#>  evaluate     0.10       2016-10-11 CRAN (R 3.3.1)                    
#>  htmltools    0.3.5      2016-03-21 CRAN (R 3.2.4)                    
#>  knitr        1.15.1     2016-11-22 CRAN (R 3.3.2)                    
#>  lazyeval     0.2.0      2016-06-12 CRAN (R 3.2.5)                    
#>  magrittr     1.5        2014-11-22 CRAN (R 3.2.2)                    
#>  memoise      1.0.0      2016-01-29 CRAN (R 3.2.3)                    
#>  R6           2.2.0      2016-10-05 CRAN (R 3.3.2)                    
#>  Rcpp         0.12.9     2017-01-14 CRAN (R 3.3.2)                    
#>  rmarkdown    1.3        2017-01-16 Github (rstudio/rmarkdown@3544f1d)
#>  rprojroot    1.2        2017-01-16 CRAN (R 3.3.2)                    
#>  stringi      1.1.2      2016-10-01 CRAN (R 3.3.2)                    
#>  stringr      1.1.0.9000 2017-01-23 Github (tidyverse/stringr@23b712c)
#>  tibble       1.2-15     2017-03-08 local                             
#>  tidyr      * 0.6.1      2017-01-10 CRAN (R 3.3.2)                    
#>  withr        1.0.2      2016-06-20 CRAN (R 3.2.5)                    
#>  yaml         2.1.14     2016-11-12 CRAN (R 3.3.2)
```

</details>


# with `rmarkdown::render()` for test.R

I kept and inspected the intermediary files.

## test.utf8.md
``` 
## # A tibble: 3 × 3
##       y     z             data
##   <int> <dbl>           <list>
## 1     1     1 <tibble [1 × 1]>
## 2     2     1 <tibble [1 × 1]>
## 3     3     2 <tibble [1 × 1]>
```

## test.knit.md

```
## # A tibble: 3 ? 3
##       y     z             data
##   <int> <dbl>           <list>
## 1     1     1 <tibble [1 ? 1]>
## 2     2     1 <tibble [1 ? 1]>
## 3     3     2 <tibble [1 ? 1]>
```

## test.html
It looks fine!

**Comment by masalmon** [comment]
Maybe I could have written a simpler example :see_no_evil:

**Comment by hadley** [comment]
This should be fixed in the latest version of tibble

**Comment by maelle** [comment]
I have installed `tibble` from Github and still get this:

``` r
library(tidyr)
#> Warning: package 'tidyr' was built under R version 3.3.2
test <- data.frame(x = letters[1:3], 
           y = 1:3,
           z = c(1, 1, 2)) %>% 
  nest(-y, -z)
print(test)
#> # A tibble: 3 Ã— 3
#>       y     z             data
#>   <int> <dbl>           <list>
#> 1     1     1 <tibble [1 Ã— 1]>
#> 2     2     1 <tibble [1 Ã— 1]>
#> 3     3     2 <tibble [1 Ã— 1]>
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info --------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.3.1 (2016-06-21)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Spanish_Spain.1252          
#>  tz       Europe/Paris                
#>  date     2017-04-20
#> Packages ------------------------------------------------------------------
#>  package    * version    date       source                           
#>  assertthat   0.2.0      2017-04-11 CRAN (R 3.3.3)                   
#>  backports    1.0.5      2017-01-18 CRAN (R 3.3.2)                   
#>  DBI          0.6-1      2017-04-01 CRAN (R 3.3.3)                   
#>  devtools     1.12.0     2016-06-24 CRAN (R 3.3.2)                   
#>  digest       0.6.12     2017-01-27 CRAN (R 3.3.2)                   
#>  dplyr        0.5.0      2016-06-24 CRAN (R 3.3.3)                   
#>  evaluate     0.10       2016-10-11 CRAN (R 3.3.1)                   
#>  htmltools    0.3.5      2016-03-21 CRAN (R 3.2.4)                   
#>  knitr        1.15.1     2016-11-22 CRAN (R 3.3.2)                   
#>  lazyeval     0.2.0      2016-06-12 CRAN (R 3.2.5)                   
#>  magrittr     1.5        2014-11-22 CRAN (R 3.2.2)                   
#>  memoise      1.0.0      2016-01-29 CRAN (R 3.2.3)                   
#>  R6           2.2.0      2016-10-05 CRAN (R 3.3.2)                   
#>  Rcpp         0.12.10    2017-03-19 CRAN (R 3.3.3)                   
#>  rlang        0.0.0.9018 2017-04-20 Github (hadley/rlang@b22ce1c)    
#>  rmarkdown    1.4        2017-03-24 CRAN (R 3.3.3)                   
#>  rprojroot    1.2        2017-01-16 CRAN (R 3.3.2)                   
#>  stringi      1.1.3      2017-03-21 CRAN (R 3.3.3)                   
#>  stringr      1.2.0      2017-02-18 CRAN (R 3.3.3)                   
#>  tibble       1.3.0.9001 2017-04-20 Github (tidyverse/tibble@bc87659)
#>  tidyr      * 0.6.1      2017-01-10 CRAN (R 3.3.2)                   
#>  withr        1.0.2      2016-06-20 CRAN (R 3.2.5)                   
#>  yaml         2.1.14     2016-11-12 CRAN (R 3.3.2)
```

</details>

Changing the locale via `Sys.setlocale("LC_ALL","English")` didn't change anything either.

**Comment by jennybc** [comment]
I think there's still more I need to attend to here in reprex. I'm not being careful about specifying UTF-8 everywhere.

**Comment by jennybc** [comment]
This has now been fixed in tibble. 

https://github.com/tidyverse/tibble/issues/216
